version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: bulma-stylus
    versions:
    - ">0.8.0"
