services:
  dev:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: base

    image: my-website-server
    ports:
      - "80:4000"
    volumes:
      - type: bind
        source: ..
        target: /workspace

    command: ["tail", "-f", "/dev/null"]
